import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import ThemeWrapper from './layout/components/ThemeWrapper';

export const metadata: Metadata = {
  title: 'xinxin',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html
      lang="cn"
      className="w-screen h-screen overflow-hidden trancy-zh-CN"
      suppressHydrationWarning
    >
      <body className="w-full h-full bg-cover bg-[url('/bg-light.png')] dark:bg-[url('/bg-dark.png')]">
        {/* 暗黑主题 */}
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange={false}
        >
          {/* 初始加载动画 */}
          <ThemeWrapper>
            <div className="w-full m-auto h-[67vh] lg:h-[80vh] ">
              {children}
            </div>
          </ThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
