import type { Metadata } from 'next';
import './globals.css';
import TopBar from './components/TopBar';
import Footer from './components/Footer';

export const metadata: Metadata = {
  title: 'xinxin',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" className="w-screen h-screen overflow-hidden trancy-zh-CN">
      <body className="w-full h-full bg-[url('/bg.png')] bg-cover">
        <div className="md:w-9/12 m-auto h-full shadow-lg ">
          <TopBar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
